language: csharp
dist: bionic
mono: 4.6.2
dotnet: 3.1.102
git:
  depth: false
env:
- DOCFX_TOOL="mono docfx.console/tools/docfx.exe"
install:
- nuget install docfx.console -ExcludeVersion
script:
- $DOCFX_TOOL metadata docfx.json
- $DOCFX_TOOL build docfx.json
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  repo: fluentmigrator/fluentmigrator.github.io
  target-branch: master
  local-dir: _site
  keep-history: true
  on:
    branch: master
